services:

  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products-msvc/ProductsAPI/Dockerfile


  products_pgdb:

    image: postgres:16.2-alpine
    
