services:

  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/ProductsAPI/Dockerfile


  products_pgdb:

    image: postgres:16.2-alpine
    

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: APIGateways/YARPAPIGateway/Dockerfile

