services:
  dev-console:
    image: ubuntu:latest  
    command: sh  
    stdin_open: true  
    tty: true  
    volumes:
     - /dev-console-data

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: APIGateways/YARPAPIGateway/Dockerfile

  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/ProductsAPI/Dockerfile


  products_pgdb:
    image: postgres:16.2-alpine

  users_pgdb:
    image: postgres:16.2-alpine

  orders_pgdb:
    image: postgres:16.2-alpine


  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/UsersAPI/Dockerfile


  ordersapi:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/OrdersAPI/Dockerfile

