services:
  yarpapigateway:
    depends_on:
      - productsapi
      - usersapi
      - ordersapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "7777:8080"
      - "7788:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres_db:
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: "-c listen_addresses='*'"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



  productsapi:
    hostname: productsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=postgres_db;Port=5432;Database=productsdb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "6000:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  usersapi:
    hostname: usersapi
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
      - ASPNETCORE_HTTPS_PORTS=8181
      - ConnectionStrings__Database=Server=postgres_db;Port=5432;Database=usersdb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6010:8180"
      - "6011:8181"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    

  ordersapi:
    hostname: ordersapi
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8280
      - ASPNETCORE_HTTPS_PORTS=8281
      - ConnectionStrings__Database=Server=postgres_db;Port=5432;Database=ordersdb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6020:8280"
      - "6021:8281"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
